### ISSUE TITLE
json-schema-faker

### ISSUE THREAD

**Issue by eXigentCoder** [rouanw/randoc#1]
Hey, I was taking a look through your library and it's very similar to one we used before to generate lots of data for performance testing. I thought I'd recommend you check out: [json-schema-faker](https://github.com/json-schema-faker/json-schema-faker )
It uses both chance.js and faker.js to generate data and might save you some time. The json-schema format is very expressive.

**Comment by rouanw** [comment]
Thanks for the link @eXigentCoder!
